== Introduction

Cherrytree is a free and open source, hierarchical, note-taking application. It can store text, images, files, links, tables, and executable snippets of code. This application is under active development. Details regarding updates can be found in Cherrytree's {changelog}[changelog].

=== About This Manual

This manual was written for Cherrytree version {revnumber}. If you are using a newer version of Cherrytree, check the {manual-web}[documentation website] for the latest version of the manual.

If you have questions, try asking in the {forum}[forum].

=== Get Involved

New contributors are welcome! We recommend that you {maintainer}[contact the project's maintainer] before working on a feature.

==== Development

Visit the GitHub {repository}[repository] to get started.

Development is currently focused on porting from Python to C++/GTKmm. These changes are located on the master branch within the {future}[future directory]. The latest stable release can also be found on the master branch. The pygi branch is a discontinued attempt to port to the python bindings for GTK3. It failed due to missing pygi bindings for core clipboard functionality.

Developers can help by addressing bugs submitted to the repository's {issues}[issues page].

==== Testing

If you find a bug, check to see if it has already been reported within the project's {issues}[issues page]. If the error is unreported, create a new issue providing as much detail as
possible.

If needed, here is a short guide on {issues-guide}[writing a proper GitHub issue].

==== Writing

The web version of the Cherrytree user manual is written using {_asciidoctor}[asciidoctor] and is {manual-repo}[maintained on GitHub]. Contributors can help with writing and proofing, or by porting the manual to a *.ctb* version intended to demonstrate Cherrytree's potential. 

==== Translation

Contact the project's {maintainer}[maintainer] to add or edit translations.

==== Resources
* {repository}[Cherrytree repository]
* link:#_running_from_source[Run from source tutorial]
* {pygtk2-doc}[PyGTK2 reference manual]
* {forum}[Cherrytree community forum]
* {cpp-tut}[C++ tutorial]
* {gtkmm-doc}[Programming with gtkmm 3]

==== Donations

Join the {supporters}[Cherrytree Supporters]!

Donations are appreciated and can be made from the {donate}[Cherrytree website].
