== Installation

Cherrytree is available for Linux and Windows.

=== Fedora (Red Hat)

[start=1]
. Download the latest installer that has a *.rpm* extension from the {download}[downloads webpage].
. Open a terminal and change to the directory containing your installation file.
. Enter the following command, replacing `cherrytree.rpm` with the name of your installation file: 
+
  sudo rpm -Uvh --force cherrytree.rpm

. Provide your password when prompted to complete the installation.

=== Ubuntu (Debian)

Cherrytree can be installed to Ubuntu via the *Ubuntu Software* application or the command line.

==== Option One: Ubuntu Software

Add the Cherrytree PPA (Personal Package Archive) to ensure that the application version installs. 

[start=1]
. Open the *Software and Updates* application.
. Go to the *Other Software* tab.
. Click *Add*.
. Enter the following snippet into the textbox:
+
  ppa:giuspen/ppa

. Click *Add Source* and enter your password when prompted.
. Confirm that the PPA is added then close the window.
+
[[figure-2.01]]
.Figure 2.01
{ubuntuinstall04}

. Click *Reload* and enter your password to install updates from the newly added source.
. Open *Ubuntu Software* and search for Cherrytree.
. Select the application and click *Install*. 
. Provide your password when prompted to begin the installation.
. Launch *Cherrytree* and confirm that the latest version of the application is installed by comparing its version number, located in the title bar, with the latest version documented in the {changelog}[changelog]. + 

==== Option Two: Command Line

[start=1]
. Download the latest installer that has a *.deb* extension from the {download}[downloads webpage].
. Open a terminal and change to the directory containing the installation file.
. Enter the following command, replacing `cherrytree.deb` with the name of your installation file: 
+
  sudo dpkg -i cherrytree.deb

. Provide your user password when prompted to begin the installation.

=== Windows

[start=1]
. Download and run the latest installer that has an *.exe* extension from the {download}[downloads webpage].

. Select a language and click *Next*.
. Accept the license and click *Next*.
. Select a directory to install the application to and click *Next*.
. (*Optional*) Select *Create a desktop shortcut* to create a shortcut to the application during the installation process. 
. Click *Next*.
. Review the provided summary then click *Install*.
. Click *Finish* to complete the installation.

NOTE: If a new version of Cherrytree is installed over a previous version, an error may occur when trying to overwrite *dbus-daemon.exe*. If so, skip the overwrite and restart your computer, then try again.
