== Quick start

This brief quick start guide covers the following material:

* User Interface
* Node Management
* Core Text Editing
* Inserting Objects
* Saving Files
* Exporting Documents

=== Interface

Cherrytree’s interface consists of four sections, highlighted in <<figure-3.01>>:

[[figure-3.01]]
.Figure 3.01
{interface}

==== Menu Bar (Red)

The menu bar contains the following menus:

* *File* - Document-management features such as opening, saving, printing, and exporting.
* *Edit* - Application preferences, basic copy and paste features, and object insertion features.
* *Formatting* - Text formatting options.
* *Tree* - Node management features.
* *Search* - Features for search and replace.
* *View* - Interface options.
* *Bookmarks* - Bookmarks are listed in this menu. They can be added by right-clicking a node within the tree view and selecting the “Add to Bookmarks” option.
* *Import* - Cherrytree can import from a variety of sources including KeepNote, NoteCase, Tomboy, HTML files, others.
* *Export* - Cherrytree documents can be exported to HTML, PDF, and Plain Text.
* *Help* - Contains “Check for updates”, an “About” section, and a link to the online manual."

==== Toolbar (Purple)

The toolbar has many commonly used options for managing nodes, formatting text, and inserting objects.

==== Tree View (Green)

Cherrytree’s tree view shows the document’s hierarchical structure of nodes.

==== Editor (Yellow)

The editor is used to read, write, edit, and delete notes. Click and hold the divider between the tree view and editor, then drag the mouse left or right to resize the two windows.

==== Interface Options

Most interface options exist within the "View" menu. <<figure-3.02>>

[[figure-3.02]]
.Figure 3.02
{view-menu}

The size of the toolbar icons is enlarged within <<figure-3.01>>. Icon size can be increased by selecting “Increase Toolbar Icon Size” or decreased with the “Decrease Toolbar Icon Size” option.

=== Node Management

Cherrytree allows you to organize notes using a link:#_nodes[tree structure]. 

==== Creating Your First Node

[start=1]
. Click the “Add Node” button, shown in <<figure-3.04>>. within the menu bar. +
+
[[figure-3.04]]
.Figure 3.04
{tree-node-add}

. Within the "New Node Properties" menu, shown in <<figure-3.05>> give your node a name and select a node type, then click the “OK” button. If you’re unsure which node type to use, please view the link:#_choosing_a_node_type[node type section] of this manual. +
+
[[figure-3.05]]
.Figure 3.05
{new-node}

==== Node Menu

Right-click a node to display a menu of the options available to it. <<figure-3.06>> +

[[figure-3.06]]
.Figure 3.06
{tree-menu}

Commonly used options include:

* *Add Node* - Create a node on the same level of hierarchy as your current node.
* *Add SubNode* - Create a child node under the currently selected node.
* *Change Node Properties* - Edit the settings of the current node.
* *Delete Node* - Delete the currently selected node.

=== Insert Objects

Objects can be inserted from the menu bar under "Edit", <<figure-3.07>>, or the toolbar, <<figure-3.08>>. 

[[figure-3.07]]
.Figure 3.07
{insert-menu}

[[figure-3.08]]
.Figure 3.08
{insert-toolbar}

The following objects can be inserted into Cherrytree documents:

* Image
* Table
* CodeBox
* File
* Link
* Anchor
* TOC (Table of Contents)
* Timestamp
* Special Character
* Horizontal Rule

=== Save Your Notes

[start=1]
. You can save your document by holding "Ctrl" and pressing "s" or clicking "File" within the menu bar and selecting the "Save" option, as shown in <<figure-3.09>>. +
+
If you have previously saved the current document, you do not need to perform steps 2 and 3. +
+
[[figure-3.09]]
.Figure 3.09
{save-menu}

. If this is your first time saving the current document, you will be prompted to select a storage type, as shown in <<figure-3.10>>. If you are unsure which type to select, please visit the link:#_storage_type[storage type section] for more details. +
+
[[figure-3.10]]
.Figure 3.10
{save-type}

. After you have selected a type, give your document a name and select a folder to save it to. <<figure-3.11>> +
+
[[figure-3.11]]
.Figure 3.11
{save-as}

=== Export the Document

[start=1]
. To export your document, click "Export" within the menu bar and select a type of document type. <<figure-3.12>> +
+
[[figure-3.12]]
.Figure 3.12
{export-menu}

. When prompted, select the scope of content to be exported then click the "OK" button. <<figure-3.13>> +
+
[[figure-3.13]]
.Figure 3.13
{export-scope}

. After you have selected a type you will be prompted to give your document a name and select a folder to save it to. <<figure-3.14>> +
+
[[figure-3.14]]
.Figure 3.14
{save-as}
