== Building from Source

You should consider building from source if you're interested in contributing to Cherrytree, installing on macOS, or having the latest features and patches as soon as they are committed.

*Skills Required*

* Command Line
*  Git

=== Fedora (Red Hat)

[start=1]
. Cherrytree requires Python 2.7. Open a terminal and check your current version of Python using the command: 
+
  python2 --version
  
. If a variant of `Python 2.7` is not returned, install it by running the following command then check the version again: 
+
  sudo yum install python2.7 python-pip
  
. Install Cherrytree's core dependencies with the command:
+
  sudo yum install pygtk2 pygtksourceview p7zip p7zip-plugins
  
. (*Optional*) Install dependencies for additional functionality:
.. To use an appindicator in systray instead of the standard systray.
+
  sudo yum install python-appindicator
  
.. For multiple instances centralization. (Double-clicking a file that is already open displays the open document instead of opening another instance of that file.)
+
  sudo yum install python-dbus
  
.. For spell check fuctionality.
+
  sudo yum install python-enchant
  
.. For better decoding support of imported and pasted text.
+
  sudo yum install python-chardet
  
. {git-clone}[Clone] or download the {repository}[Cherrytree repository]. 
. Open a terminal, change to the directory containing your local copy of Cherrytree, and run: 
+
  python2 cherrytree

=== Ubuntu (Debian)

[start=1]
. Cherrytree requires Python 2.7. Open a terminal and check your current version of Python using the command:
+
  python2 --version
  
. If a variant of `Python 2.7` is not returned, install it by running the following command then check the version again:
+
  sudo apt install python2.7 python-pip

. Install Cherrytree's core dependencies with the command:
+
  sudo apt install python-gtk2 python-gtksourceview2 p7zip-full libcanberra-gtk-module

. (*Optional*) Install dependencies for additional functionality:
.. To use an appindicator in systray instead of the standard systray.
+
  sudo apt install python-appindicator
  
.. For multiple instances centralization. (Double-clicking a file that is already open displays the open document instead of opening another instance of that file.)
+
  sudo apt install python-dbus
  
.. For spell check fuctionality.
+
  sudo apt install python-enchant

.. For better decoding support of imported and pasted text.
+
  sudo apt install python-chardet
  
  . {git-clone}[Clone] or download the {repository}[Cherrytree repository]. 
  . Open a terminal, change to the directory containing your local copy of Cherrytree, and run: 
+
    python2 cherrytree

[[build-windows]]
=== Windows

Building from source in Windows is more complicated than in other operating systems.

link:#_installing_python_2_7[*Steps 1-8:*] Installing Python2.7 and adding it to environment variables. +
link:#_installing_cherrytree_dependencies[*Steps 9-16:*] Installing Cherrytree dependencies. +
link:#_configuring_the_cherrytree_directory[*Steps 17-20:*] Configuring the Cherrytree directory.

==== Installing Python 2.7

[start=1]
. If a variant of Python 2.7 is not installed to your machine, navigate to the {python-downloads}[Python Releases for Windows page] and click *Latest version of Python 2*.

. Download and run the *Windows x86 MSI installer* version, then follow its installation steps.
. (*Optional*) Navigate to the folder where you installed Python 2.7 and rename the *python* application to *python2* to avoid conflicting with Python3.

. Copy the path of your installation directory.

. Open your environment variable settings.
+
NOTE: Click {win7-vars-link}[here] for instructions to add environment variables in Windows 7.

. Select *Path* and click *Edit*. 

. Click *New* then paste the path of your Python 2.7 installation into the text field. 
. Click *Ok* to close the window.

==== Installing Cherrytree Dependencies

[start=9]
. {gtk2-bundle}[Download the GTK2 Windows bundle].
. {7zip}[Unzip] the GTK2 bundle.
. Open the bundle, move into the *bin* folder, then copy its path and add it to your environment variables. 
+
NOTE: For example, if you move the bundle into your *C:* drive, your path should look like `C:\gtk2\bin`.

. {pygtk-all-in-one}[Download the PYGTK installer].
. Run the installation file and follow its steps to install. Ensure *PYGtkSourceView2* is toggled on the *Custom Setup* page.
+
[[figure-3.01]]
.Figure 3.01
{pygtkwin}

. {py2lib}[Download python 2.7 lib files].
. {7zip}[Unzip] the folder and move the content from *C_Python27_Lib* to the *Lib* folder within your Python 2.7 installation. 

. (*Optional*) Open *Command Prompt* and install dependencies for additional functionality using the commands: 
.. For spell check functionality.
+
  python2 -m pip install pyenchant
  
.. For better decoding support of imported and pasted text.
+
  python2 -m pip install chardet


==== Configuring the Cherrytree Directory

[start=17]
. {git-clone}[Clone] or download the {repository}[Cherrytree repository]. 
. {portable7zip}[Download a portable version of 7zip], which is required to password-protect files. 
. Extract its content and move the *7za.exe* file into the root folder of your local Cherrytree directory.
. Open *Command Prompt*, change to the directory containing your local copy of Cherrytree, and run:
+
  python2 cherrytree


=== macOS (Not Tested)

Cherrytree is not supported for macOS but can be installed from source using {homebrew}[Homebrew].

[start=1]
. Install {mac-python}[Python 2.7].
. Install {homebrew}[Homebrew].
. Install Cherrytree's core dependencies using Homebrew and the following commands:
+
  brew install gtk-mac-integration
+
  brew install pygtksourceview
+
  brew install dbus
+
  brew install dbus-glib
  
. (*Optional*) Install dependencies for additional functionality using PIP (a package manager for Python):
.. For multiple instances centralization. (Double-clicking a file that is already open displays the open document instead of opening another instance of that file.)
+
  python2 -m pip install dbus-python

.. For spell check functionality.
+
  python2 -m pip install pyenchant
  
.. For better decoding support of imported and pasted text.
+
  python2 -m pip install chardet 
  
  . {git-clone}[Clone] or download the {repository}[Cherrytree repository]. 
  . Open a terminal, change to the directory containing your local copy of Cherrytree, and run: 
+
    python2 cherrytree


NOTE: View this {mac-build}[discussion] for more information about building Cherrytree on macOS. 
