== Quick start

This brief quick start guide covers the following material:

* User Interface
* Node Management
* Core Text Editing
* Inserting Objects
* Saving Files
* Exporting Documents

=== Interface

// TODO: Highlight sections of the interface using colors AND numbers for better accessibility.

Cherrytree's interface consists of four sections, highlighted in <<figure-4.01>>.

[[figure-4.01]]
.Figure 4.01
{interface}

[[menu-bar]]
==== Menu Bar (Red)

The menu bar contains the following menus:

* *File* - Document-management features such as opening, saving, printing, and exporting.
* *Edit* - Application preferences, basic copy and paste features, and object insertion features.
* *Formatting* - Text formatting options.
* *Tree* - Node management features.
* *Search* - Features for search and replace.
* *View* - Interface options.
* *Bookmarks* - Bookmarks are listed in this menu. They can be added by right-clicking a node within the tree view and selecting *Add to Bookmarks*.
* *Import* - Cherrytree can import from a variety of sources including KeepNote, NoteCase, Tomboy, HTML files, others.
* *Export* - Cherrytree documents can be exported to HTML, PDF, and Plain Text.
* *Help* - Contains *Check for updates*, an *About* section, and a link to the online manual.

[[toolbar]]
==== Toolbar (Purple)

The toolbar contains options for managing nodes, formatting text, and inserting objects.

[[tree-view]]
==== Tree View (Green)

Cherrytree's tree view shows the document's hierarchical structure of nodes.

[[editor]]
==== Editor (Yellow)

The editor is used to read, write, edit, and delete notes. Click and hold the divider between the tree view and editor, then drag the mouse left or right to resize the two windows.

==== Interface Options

Most interface options exist within the *View* menu.

[[figure-4.02]]
.Figure 4.02
{view-menu}

The size of the toolbar icons is enlarged within <<figure-4.01>>. Icon size can be increased by selecting *Increase Toolbar Icon Size* or decreased with *Decrease Toolbar Icon Size*.

You can also increase the size of text within the node view and editor with `CTRL`+`[Mousewheel]`.

=== Node Management

Cherrytree allows you to organize notes using a link:#_nodes[tree structure]. 

==== Creating Your First Node

[start=1]
. Click *Add Node* within the toolbar, shown in <<figure-4.04>>.
+
[[figure-4.04]]
.Figure 4.04
{tree-node-add}

. Within *New Node Properties*, give your node a name and select a node type, then click *OK*. If you're unsure which node type to use, view link:#_text[*7. Text*] of this manual. 
+
[[figure-4.05]]
.Figure 4.05
{new-node}

==== Node Menu

Right-click a node to display a menu of the options available to it.

[[figure-4.06]]
.Figure 4.06
{tree-menu}

Commonly used options include:

* *Add Node* - Create a node on the same hierarchical level as your selected node.
* *Add SubNode* - Create a child node under the selected node.
* *Change Node Properties* - Edit the settings of the current node.
* *Delete Node* - Delete the selected node.

=== Insert Objects

Objects can be inserted from the *Edit* menu or the link:#toolbar[toolbar].

[[figure-4.07]]
.Figure 4.07
{insert-menu}

[[figure-4.08]]
.Figure 4.08
{insert-toolbar}

Cherrytree supports the following objects:

* link:#_images[Image]
* link:#_tables[Table]
* link:#_codebox[CodeBox]
* link:#file-object[File]
* link:#_links[Link]
* link:#_anchors[Anchor]
* link:#_table_of_contents[TOC (Table of Contents)]
* link:#_time_stamps[Timestamp]
* link:#_special_characters[Special Character]
* link:#_horizontal_rule[Horizontal Rule]

=== Save Your Notes

[start=1]
. You can save your document with `CTRL`+`S` or by clicking *File* within the menu bar and selecting *Save*.
+
If you have previously saved the current document, you do not need to perform steps 2 and 3.
+
[[figure-4.09]]
.Figure 4.09
{save-menu}

. If this is your first time saving the current document, select a storage type then click *OK*.
+
NOTE: See link:#_storage_types[*Storage Types*] and link:#_password_protection[Password Protection].
+
[[figure-4.10]]
.Figure 4.10
{save-type}

. After you have selected a type, give your document a name and select a folder to save it to. 
+
[[figure-4.11]]
.Figure 4.11
{save-as}

=== Export the Document

[start=1]
. To export your document, click *Export* within the menu bar and select a type of document type.
+
[[figure-4.12]]
.Figure 4.12
{export-menu}

. When prompted, select the scope of content to be exported then click *OK*.
+
[[figure-4.13]]
.Figure 4.13
{export-scope}

. After you have selected a type you will be prompted to give your document a name and select a folder to save it to.
+
[[figure-4.14]]
.Figure 4.14
{save-as}
