== Quick start

This quick start guide covers the following material:

* link:#_interface[User Interface]
* link:#_node_management[Node Management]
* link:#_insert_objects[Inserting Objects]
* link:#_save_your_notes[Saving Files]
* link:#_export_a_document[Exporting Documents]

=== Interface

Cherrytree's interface consists of four sections, highlighted in <<figure-4.01>>.

[[figure-4.01]]
.Figure 4.01
{interface}

[[menu-bar]]
==== 1. Menu Bar 

The menu bar contains the following menus:

* *File* - Document-management features such as opening, saving, printing, and exporting.
* *Edit* - Application preferences, basic copy and paste features, and object insertion features.
* *Formatting* - Text formatting options.
* *Tree* - Node management features.
* *Search* - Features for search and replace.
* *View* - Interface options.
* *Bookmarks* - A list of bookmarked nodes. Nodes can be added to bookmarks by right-clicking the node within the tree view and selecting *Add to Bookmarks*.
* *Import* - Cherrytree can import from a variety of sources including KeepNote, NoteCase, Tomboy, HTML files, others.
* *Export* - Cherrytree documents can be exported to HTML, PDF, and Plain Text.
* *Help* - Contains *Check for updates*, an *About* section, and a link to the online manual.

[[toolbar]]
==== 2. Toolbar 

The toolbar contains options for managing nodes, formatting text, and inserting objects.

[[tree-view]]
==== 3. Tree View

Cherrytree's tree view shows the document's hierarchical structure of nodes.

[[editor]]
==== 4. Editor 

The editor is used to read, write, edit, and delete notes. Click and hold the divider between the tree view and editor, then drag the mouse left or right to resize the two windows.

==== Interface Options

Most interface options exist within the *View* menu, located in the link:#_interface[menu bar].

The size of the toolbar icons is enlarged within <<figure-4.01>>. Icon size can be increased by selecting *Increase Toolbar Icon Size* in the *View* menu or decreased with *Decrease Toolbar Icon Size*.

You can also increase the size of text within the node view and editor with `CTRL`+`[Mousewheel]`.

=== Node Management

Cherrytree allows you to organize notes using a link:#_nodes[tree structure]. 

==== Creating Your First Node

[start=1]
. Click *Tree* > *Add Node* to display the *New Node Properties* menu.
. Enter a *Node Name*.
. Select a *Node Type* then click *OK*. 
+
NOTE: View link:#_text[*7. Text*] of this manual for details about *Node Type*. 

==== Node Menu

Right-click a node to display a menu of the options available to it.

Commonly used options include:

* *Add Node* - Creates a node on the same hierarchical level as your selected node.
* *Add SubNode* - Creates a child node under the selected node.
* *Change Node Properties* - Edit the settings of the current node.
* *Delete Node* - Deletes the selected node.

See link:#_nodes[*6. Nodes*] for more detail.

=== Insert Objects

Objects can be inserted from the *Edit* menu.

Cherrytree supports the following objects:

* link:#_images[Image]
* link:#_tables[Table]
* link:#_codebox[CodeBox]
* link:#file-object[File]
* link:#_links[Link]
* link:#_anchors[Anchor]
* link:#_table_of_contents[TOC (Table of Contents)]
* link:#_time_stamps[Timestamp]
* link:#_special_characters[Special Character]
* link:#_horizontal_rule[Horizontal Rule]


See link:#_objects[*8. Objects*] for more detail.

=== Save Your Notes

[start=1]
. Documents are saved by pressing `CTRL`+`S` or by selecting *Save* from the *File* menu.
+
If you have previously saved the current document, you do not need to perform steps 2 and 3.

. If this is your first time saving the current document, select a storage type then click *OK*.
+
NOTE: See link:#_storage_types[*Storage Types*] and link:#_password_protection[Password Protection] for more details.

. Name the document and select a folder to save it to. 

See link:#_saving[*5.2 Saving*] for more detail.

=== Export a Document

[start=1]
. Open the *Export* menu and select a document type.
. Select the scope of content to be exported then click *OK*.
. Name the exported document and select a folder to save it to.

See link:#_exporting[*5.5 Exporting*] for more detail.
