== Files

Documents are managed from the *File* menu or toolbar.

=== Creating and Opening

To create a new document, select *New Instance* from the *File* menu.

To open an existing file:
[start=1]
. Select *Open File* from the *File* menu.
. Select a document to open.
. Click *Open*. 

Recently used documents can be opened more quickly by selecting the document name within the *File* > *Recent Files* submenu. 

=== Saving

==== Saving to the Current File
Save your document by pressing `CTRL`+`S` or by selecting *Save* from the *File* menu.

NOTE: If this your first time saving the current document, see the link:#_saving_to_a_new_file[save to a new file section] below.

==== Saving to a New File

[start=1]
. Save your document to a new file by pressing `CTRL`+`SHIFT`+`S` or by selecting *Save As* from the *File* menu.

. Select a link:#_storage_types[storage type].

. Name the document and select a folder to save it to.

==== Save and Vacuum

Vacuuming rebuilds the database file, packing it into a minimal amount of disk space. Empty space is left behind when a large amount of data is deleted from a database. Frequent inserts, updates, and deletes can also cause the database file to become fragmented &mdash; where data for a single table or index is scattered around the database file. 

This feature should be used periodically when working with SQLite files to keep the database from assuming more space than necessary.
  
NOTE: Visit the {vacuum}[SQLite documentation page for the vacuum command] to learn more about vacuuming.

==== Storage Types

When saving a document for the first time, Cherrytree prompts you to choose between two file formats, SQLite and XML.

*SQLite* is a self-contained database and has a *.ctb* or *.ctx* extension when used with Cherrytree. Instead of loading the complete document at runtime, Cherrytree only accesses the tree structure and currently selected node. This makes opening your document faster but may slow functions such as searching and selecting nodes when they're used for the first time in a session. 

Performance loss with SQLite is lower than with XML, making it better suited for larger documents. The link:#_save_and_vacuum[Save and Vacuum] feature should be used periodically to keep SQLite files compact.

*XML* is a markup language and has a *.ctd* or  *.ctz* extension when used with Cherrytree. The files are fully loaded at runtime, making searching and navigating through nodes faster, but slowing the initial load time.

XML is more accessible and easier to convert to other file types but should not be used with large documents. 

==== Password Protection

Password-protected files are compressed and locked with {7zip}[7zip], an open source file archiver. 

CAUTION: Other applications might not provide functionality to unlock files that have been locked by Cherrytree. 

==== Changing Passwords

To change the password of a protected file:
[start=1]
. Open the file in Cherrytree.
. Select *Save-as* from the *File* menu. 
. link:#_saving_to_a_new_file[Save the document as a new file].
.. Select a protected storage type. 
.. Use a new password to protect this copy of the document. 

=== Page Setup and Printing

*Page Setup*, found in the *File* menu, contains options for the document size, orientation, and margins.

To print a document, click *File* > *Print*, then choose between one of the following options when prompted:

* Selected Text Only
* Selected Node Only
* Selected Node and Subnodes
* All the Tree

Select *New Node in New Page* to apply page breaks at the end of nodes within the printed document. 

=== Importing

Notes are imported into Cherrytree from the *Import* menu, located within the link:#menu-bar[menu bar].

[start=1]
. Select one of the following options from the *Import* menu:

** From CherrTree File
** From Plain Text File
** From Folder of Plain Text Files
** From HTML File
** From Folder of HTML Files
** From Basket Folder
** From EssentialPIM HTML File
** From Gnote Folder
** From KeepNote Folder
** From Keynote File
** From Knowit File
** From Leo File
** From Mempad File
** From NoteCase File
** From RedNotebook Folder
** From Toyboy Folder
** From Treepad Lite File
** From TuxCards File
** From Zim Folder

. Select a file or folder to import then click *Open*.
. In the *Who is the parent?* menu, select one of the following options:
** *The Tree Root* - Each imported file is added to a top-level node.
** *The Selected Node* - Each imported file is added to a child node of the selected node.
. Click *OK*.

NOTE: This process may take a few minutes when importing many files or larger files.

=== Exporting

To export notes from another file:

[start=1]
. Select one of the following options from the *Export* menu:

** Export to PDF
** Export to HTML
** Export to Multiple Plain Text Files
** Export to Single Plain Text File
** Export to CherryTreeDocument

. Within the *Involved Nodes* menu, select the scope of your document to be exported:

** Selected Text Only
** Selected Node Only
** Selected Node and Subnodes
** All in Tree

. Additional options are available depending on the export type:

** *Include Node name* - Displays the name of each Node at the top of its page. This may be redundant if you have headers within the pages of your notes.
** *New Node in New Page* - Applies page breaks at the end of nodes within the exported document.
** *Links Tree in Every Page* - When enabled all web pages contain a table of contents. If this option is disabled, only the *index.html* contains a table of contents.

When exporting to HTML, all nodes are copied to the root folder of your chosen directory as *.html* files. The main HTML file is named *index.html*.

=== Command Line

Cherrytree supports command line argument for starting the application via command line.

==== Cherrytree Command

|===
|_python2 cherrytree_ | Opens Cherrytree.
|===

==== Positional arguments:

|===
|_filepath_ | Defines the document to open in Cherrytree. Replace _filepath_ with the path of a file.
|===

==== Optional arguments:

|===
| -h +
--help | Displays a list of command-line options.

| -n __node_name__ +
--node __node_name__ | Opens a document and selects the specified node. Replace __node_name__ with the node to select.

| -x __direcotry_path__ +
--export_to_html_dir __direcotry_path__ | Exports a document as HTML. Replace __direcotry_path__ with the path of the folder to save the HTML.

| -t __direcotry_path__ +
--export_to_txt_dir __direcotry_path__ | Exports a document as Plain Text. Replace __direcotry_path__ with the path of the folder to save the Plain Text.

|-w +
--export_overwrite | Overwrite an existing export.
|===

NOTE: Command line arguments are available in Linux but may only be available in Windows when the application is link:#build-windows[built from source]. 
