== Objects

Objects can be inserted from the menu bar under *Edit*, <<figure-8.01>>, or the toolbar, <<figure-8.02>>. Some objects can and also be pasted directly into Cherrytree. 

[[figure-8.01]]
.Figure 8.01
{insert-menu}

[[figure-8.02]]
.Figure 8.02
{insert-toolbar}

=== Images

==== Inserting Images

[start=1]
. Open the link:#_objects[*Edit* menu] and click *Insert Image*.
. Select the image to be uploaded and click *Open*. 
. (*Optional*) The selected image will be displayed in a simplistic editor, shown in <<figure-8.03>>, which can be used to rotate or scale the content. 
+
[[figure-8.03]]
.Figure 8.03
{img-props}
+
<<figure-8.03>> has been highlighted to indicate the parts of its interface.

* *Red* - Displays the image uploaded in *Step 2*.
* *Purple* - Allows for the editing of the image's dimensions. Height and Width are linked each other to maintain the content's aspect ratio.
* *Yellow* - Rotate the image counter-clockwise 90&deg;.
* *Green* - Rotate the image clockwise 90&deg;.
. Click *OK* to complete the insertion.

==== Editing Images

Right-click an image to display its menu of options, <<figure-8.04>>.

[[figure-8.04]]
.Figure 8.04
{edit-image}

* *Cut Image* - Move the selected image to your clipboard. The image can then be pasted elsewhere.
* *Copy Image* - Copy the selected image to your clipboard. A copy of the image can then be pasted elsewhere.
* *Delete Image* - Delete the selected image.
* *Edit Image* - Rotate or scale the image, shown in <<figure-8.03>>
* *Save Image as PNG* - Save a copy of the selected image to your computer.
* *Edit Link* - Apply or edit the link of the selected image. See link:#_links[8.5 Links] for more information about links.
* *Dismiss Link* - Remove an existing link from the selected image. This option will only appear if the image has an assigned link.

NOTE: Cherrytree does not support wrapping text around images at this time.

=== Tables

==== Creating a New Table

[start=1]
. Open the link:#_objects[*Edit* menu] and click *Insert Table*.
. (*Optional*) The *Insert Table* menu will be displayed and can be used to define the properties of the table.
+
[[figure-8.05]]
.Figure 8.05
{insert-table}
+
* *Rows* - Defines the number of rows to be in the table in the addition to the header row.
* *Columns* - Defines the number of columns to be in the table.
* *Min Width* - Defines the lowest number of pixels in width that a column must have.
* *Max Width* - Defines the highest number of pixels in width that a column can have.
* *Import from CSV File* - Imports data from a *.csv* file.
+
IMPORTANT: *.csv* data should be separated by a comma delimiter.
+
NOTE: Cherrytree may take a few minutes to upload a large file. Please be patient. 

. Click *OK* to complete the insertion.

==== Managing Columns

Click a column title to display a menu listing actions for that column. <<figure-8.06>>

[[figure-8.06]]
.Figure 8.06
{table-column}

* *Rename Column* - Change the title of the selected column.
* *Delete Column* - Delete the selected column.
* *Add Column* - Add a new column to the right of the selected column.
* *Move Column Left* - Switch the placement of the selected column with that of the column to its immediate left. Nothing will happen if there is no column left of the selected column.
* *Move Column Right* -Switch the placement of the selected column with that of the column to its immediate right.  Nothing will happen if there is no column right of the selected column.

==== Managing Rows

A table row can be edited by right-clicking any of its cells. <<figure-8.07>>

[[figure-8.07]]
.Figure 8.07
{edit-table}

* *Cut Table* - Move the selected table to your clipboard. The table can then be pasted elsewhere.
* *Copy Table* - Copy the selected table to your clipboard. A copy of the table can then be pasted elsewhere.

* *Delete Table* - Delete the selected table.

* *Add Row* - Add a new row underneath the selected row.

* *Cut Row* - Move the selected row to your clipboard. The row can then be pasted elsewhere.

* *Copy Row* - Copy the selected row to your clipboard. A copy of the row can then be pasted elsewhere.

* *Paste Row* - Paste a row from your clipboard underneath the selected row.

* *Delete Row* - Delete the selected row.

* *Move Row Up* - Switch the placement of the selected row with that of the row immediately above it. Nothing will happen if there is no row above the selected row.

* *Move Row Down* - Switch the placement of the selected row with that of the row immediately below it. Nothing will happen if there is no row below the selected row.

* *Sort Rows Descending* - References the first column to sort the selected table numerically then alphabetically, from bottom to top.

* *Sort Rows Ascending* - References the first column to sort the selected table numerically then alphabetically, from top to bottom.

* *Edit Table Properties* - Edit the *Column Properties*, discussed in <<figure-8.05>>, of the selected table.

* *Table Export* - Export the selected table to a *.csv* file containing data separated by comma delimiters.

==== Writing to Tables

Double-click a cell to open a textbox within it.

WARNING: Clicking outside of a table before closing a textbox will discard all changes to that textbox. To write changes to a textbox within a table cell, you must click to another cell, press *Enter*,  or press *Tab*. This has been reported, but is unlikely to be patched in this version of Cherrytree.

NOTE: Tables currently only support plain text. 

Right-click the textbox to display a menu of its actions and properties. <<figure-8.08>>

[[figure-8.08]]
.Figure 8.08
{cell-menu}

* *Cut* - Move the selected text to your clipboard. The row can then be pasted elsewhere.
* *Copy* - Copy the selected text to your clipboard. A copy of the table can then be pasted elsewhere.
* *Paste* - Paste the text from your clipboard to the cursor position.
* *Delete* - Delete the selected text.
* *Select All* - Select all of the text within the textbox.
* *Input Methods* - Select from one of the following input methods:
** System (Default)
** None
** Amharic(EZ+)
** Cedilla
** Cyrillic (Transliterated)
** Inuktitut (Transliterated)
** IPA
** Multipress
** Thai-Lao
** Tigrigna-Eritrean (EZ+)
** Tigrigna-Ethiopian (EZ+)
** Vietnamese (VIQR)
** Windows IME
* *Insert Unicode Control Character* - Select from one of the following unicode controls:
** *LRM* - Left-to-right mark
** *RLM* - Right-to-left mark
** *LRE* - Left-to-right embedding
** *RLE* - Right-to-left embedding
** *LRO* - Left-to-right override
** *RLO* - Right-to-left override
** *PDF* - Pop directional formatting
** *ZWS* - Zero width space
** *XWJ* - Zero width joiner
** *XWNJ* - Zero width non-joiner
* *Insert NewLine* - Adds a newline character to the current cursor position.
+ 
NOTE: This will not be noticeable until the textbox is closed.

=== Codebox

content

*Executing*

[[file-object]]
=== Files

Content

=== Links

Content

=== Anchors

Content

=== Table of Contents

Content

=== Time Stamps

Content

=== Special characters

Content

=== Horizontal Rule
