== Objects

Objects can be inserted from the *Edit* menu, located in the menu bar. Some objects can also be pasted directly into Cherrytree. 

=== Images

==== Inserting Images

[start=1]
. Select *Insert Image* from the *Edit* menu.
. Select an image to be uploaded and click *Open*. 
. (*Optional*) The selected image is displayed in the simplistic editor shown in <<figure-8.01>>, which can be used to rotate or scale the content. 
+
[[figure-8.01]]
.Figure 8.01
{img-props}
+
<<figure-8.01>> has been highlighted to indicate the parts of its interface.

* *One* - Rotates the image counter-clockwise 90&deg;.
* *Two* - Displays the image uploaded in *Step 2*.
* *Three* - Rotates the image clockwise 90&deg;.
* *Four* - Options for defining the image's dimensions. Height and Width are linked to each other to maintain the content's aspect ratio.
. Click *OK* to complete the insertion.

Cherrytree does not support wrapping text around images at this time.

==== Editing Images

Right-click an image to display its menu of options.

* *Cut Image* - Moves the selected image to your clipboard. The image can then be pasted elsewhere.
* *Copy Image* - Copies the selected image to your clipboard. A copy of the image can then be pasted elsewhere.
* *Delete Image* - Delete the selected image.
* *Edit Image* - Displays the window shown in <<figure-8.01>>
* *Save Image as PNG* - Saves a copy of the selected image to your computer.
* *Edit Link* - Apply or edit the link of the selected image. 
+
NOTE: See link:#_links[*8.5 Links*] for more information about links.

* *Dismiss Link* - Removes an existing link from the selected image. This option only appears if the image has an assigned link.

=== Tables

==== Creating a New Table

[start=1]
. Select *Insert Table* from the *Edit* menu to display the *Insert Table* menu.
. The Insert Table menu defines the size of the table and provides *.csv* import availability.
+
* *Rows* - Defines the number of rows to be in the table in the addition to the header row.
* *Columns* - Defines the number of columns to be in the table.
* *Min Width* - Defines the lowest number of pixels in width that a column must have.
* *Max Width* - Defines the highest number of pixels in width that a column can have.
* *Import from CSV File* - Imports data from a *.csv* file. Data should be separated by a comma delimiter.
+
NOTE: Cherrytree may take a few minutes to upload a large file.

. Click *OK* to complete the insertion.

==== Managing Columns

Click a column title to display a menu listing actions for that column. 

* *Rename Column* - Changes the title of the selected column.
* *Delete Column* - Deletes the selected column.
* *Add Column* - Adds a new column to the right of the selected column.
* *Move Column Left* - Switches the placement of the selected column with that of the column to its immediate left. Nothing happens if there is no column left of the selected column.
* *Move Column Right* - Switches the placement of the selected column with that of the column to its immediate right.  Nothing happens if there is no column right of the selected column.

==== Managing Rows

Right-clicking any cell in a table provides the following options:

* *Cut Table* - Moves the selected table to your clipboard. The table can then be pasted elsewhere.
* *Copy Table* - Copies the selected table to your clipboard. A copy of the table can then be pasted elsewhere.
* *Delete Table* - Deletes the selected table.
* *Add Row* - Adds a new row underneath the selected row.
* *Cut Row* - Moves the selected row to your clipboard. The row can then be pasted elsewhere.
* *Copy Row* - Copies the selected row to your clipboard. A copy of the row can then be pasted elsewhere.
* *Paste Row* - Pastes a row from your clipboard underneath the selected row.
* *Delete Row* - Deletes the selected row.
* *Move Row Up* - Switches the placement of the selected row with that of the row immediately above it. Nothing happens if there is no row above the selected row.
* *Move Row Down* - Switches the placement of the selected row with that of the row immediately below it. Nothing happens if there is no row below the selected row.
* *Sort Rows Descending* - References the first column to sort the selected table numerically then alphabetically, from bottom to top.
* *Sort Rows Ascending* - References the first column to sort the selected table numerically then alphabetically, from top to bottom.
* *Edit Table Properties* -  Displays the *Edit Table Properties* menu, providing options to define a minimum and maximum width of columns.
** *Min Width* - Columns are always at least `x` pixels wide, where `x` represents the number provided. 
** *Max Width* - Columns cannot be wider than `x` pixels in width, where `x` represents the number provided. If the content exceeds the maximum width, text wraps to the next line within the cell.
* *Table Export* - Exports the selected table to a *.csv* file containing data separated by comma delimiters.

==== Writing to Tables

Tables currently only support link:#_plain_text[plain text]. Double-click a cell to open a textbox within it.

WARNING: Clicking outside of a table before closing a textbox discards all changes to that textbox. To write changes to a textbox within a table cell, you must click to another cell, press *Enter*,  or press *Tab*. This has been reported but is unlikely to be patched in this version of Cherrytree.

Right-click the textbox to display a menu of its actions and properties.

* *Cut* - Moves the selected text to your clipboard. The row can then be pasted elsewhere.
* *Copy* - Copies the selected text to your clipboard. A copy of the table can then be pasted elsewhere.
* *Paste* - Pastes the text from your clipboard to the cursor position.
* *Delete* - Deletes the selected text.
* *Select All* - Selects the text within the textbox.
* *Input Methods* - Select from one of the following input methods:
** System (Default)
** None
** Amharic (EZ+)
** Cedilla
** Cyrillic (Transliterated)
** Inuktitut (Transliterated)
** IPA
** Multipress
** Thai-Lao
** Tigrigna-Eritrean (EZ+)
** Tigrigna-Ethiopian (EZ+)
** Vietnamese (VIQR)
** Windows IME
* *Insert Unicode Control Character* - Select from one of the following Unicode control characters:
** *LRM* - Left-to-right mark
** *RLM* - Right-to-left mark
** *LRE* - Left-to-right embedding
** *RLE* - Right-to-left embedding
** *LRO* - Left-to-right override
** *RLO* - Right-to-left override
** *PDF* - Pop directional formatting
** *ZWS* - Zero width space
** *XWJ* - Zero width joiner
** *XWNJ* - Zero width non-joiner
* *Insert NewLine* - Adds a newline character to the current cursor position.
+ 
NOTE: Newlines within table cells are not noticeable until the textbox is closed.

=== Codebox

A codebox is a contained, executable section of syntax-highlighted text, which can be inserted into link:#_rich_text[Rich Text] nodes. A link:#_rich_text[Rich Text] node can contain more than one codebox for any of the link:#_supported_languages[supported languages]. 

NOTE: See link:#_automatic_syntax_highlighting[*7.3 Automatic Syntax Highlighting*] for more details about syntax highlighting.

==== Inserting a Codebox

[start=1]

. Select *Insert Codebox* from the *Edit* menu.
. (*Optional*) Change the codebox type within the *Insert Codebox* menu:
+
* *Plain Text* - Restricts the codebox to link:#_plain_text[plain text].
* *Automatic Syntax Highlighting* - Applies link:#_automatic_syntax_highlighting[automatic syntax highlighting] to the codebox. (Default)
* *Choose a language* - Select from any of the link:#_supported_languages[supported languages].

. (*Optional*) - Define the codebox size:
+
* *Width* - Defines the width of the codebox.
** *Pixels* - Defines the width in pixels. (Default)
** *% (Percentage)* -  Defines the width as a percentage. This assigns a dynamic width that changes alongside changes in the window's width.
* *Height* - Defines the height of the codebox in pixels.

. (*Optional*) Select any additional options:
+
* *Show Line Numbers* - Display line numbers within the left margin of the codebox.
* *Highlight Matching Brackets* - Highlights the corresponding bracket of the selected opening or closing bracket. 

. Click *OK* to complete the insertion.

==== Editing a Codebox

Right-click a codebox to display its options.

* *Change CodeBox Properties* - Displays a menu similar to the *Insert CodeBox* menu.

* *Execute CodeBox Code* - Executes the code within the codebox. 
+
NOTE: See link:#_executing_a_codebox[*Executing a Codebox*] for more details.

* *CodeBox Load From Text File* - Imports code from a file. This function is not restricted to files that have a *.txt* extension.
* *CodeBox Save To Text File* - Exports the content of a codebox to a file. The file can have any extension. 
* *Cut CodeBox* - Moves the selected codebox to your clipboard. The codebox can then be pasted elsewhere.
* *Copy CodeBox* - Copies the selected codebox to your clipboard. A copy of the codebox can then be pasted elsewhere.
* *Delete CodeBox* - Delete the selected codebox.
* *Delete CodeBox Keep Content* - Replace the current codebox with a link:#_plain_text[plain text] copy of its content.
* *Increase CodeBox Width* - Increase the width of the selected codebox by 9% if it is defined as a percentage or 15px if it is defined in pixels.
* *Decrease CodeBox Width* - Decrease the width of the selected codebox by 9% if it is defined as a percentage or 15px if it is defined in pixels.
* *Increase CodeBox Height* - Increase the height of the selected codebox by 15 pixels.
* *Decrease CodeBox Height* - Decrease the height of the selected codebox by 15 pixels.

==== Executing a Codebox

A codebox that is set to link:#_automatic_syntax_highlighting[automatic syntax highlighting] can be executed from Cherrytree, assuming you have its assigned language installed to your machine. 

*To execute a node:*
[start=1]
. Right-click a codebox and select *Execute Codebox code*.
. When prompted, click *OK* to confirm that you want to execute the code.

Some languages require an execution command to be assigned to the language before the code can be executed. 

NOTE: See link:#_plain_text_and_code[*9.4 Plain Text and Code*] for details on assigning a command.

[[file-object]]
=== Files

Any file that is less than 10MB can be attached to a link:#_rich_text[Rich Text] node. link:#_rich_text[Rich Text] nodes can contain any number of attached files. 

==== Inserting a File

[start=1]
. Select *Insert File* from the *Edit* menu.
. Select a file and click *OK*.
+
NOTE: The file must be less than 10MB. 

==== Editing a File

Right-click a node to display its options.

* *Cut Embedded File* - Moves the selected file to your clipboard. The file can then be pasted elsewhere.
* *Copy Embedded File* - Copies the selected file to your clipboard. A copy of the file can then be pasted elsewhere.
* *Delete Embedded File* - Deletes the attached file.
* *Open File* - Opens the attached file.
+
IMPORTANT: Attached files should be closed before closing their host document(s).

* *Save As* - Saves a copy of the selected file to your machine.

=== Links

Text and images within link:#_rich_text[rich text] nodes can be linked to websites, files, folders, or nodes.

==== Inserting a Link

[start=1]

. Select *Insert/Edit Link* from the *Edit* menu to display the *Insert Link* menu.
. Choose from the following options:
+
* *To Website* - Routes the link to a website address.
* *To File* - Routes the link to a file on your machine.
* *To Folder* - Routes the link to a folder on your machine.
* *To Node* - Routes the link to a node within the document.
* *Anchor Name (Optional)* - Routes the link to a particular anchor within the selected node. +
+
NOTE: See link:#_anchors[*8.6 Anchors*] to learn more about anchors.


. Click *OK* to complete the insertion.

==== Editing a Link

Right-click a link to display its options.

* *Edit Link* - Displays the *Insert/Edit* menu for the selected link.
* *Cut Link* - Moves the selected link to your clipboard. The link can then be pasted elsewhere.
* *Copy Link* - Copies the selected link to your clipboard. A copy of the link can then be pasted elsewhere.
* *Dismiss Link* - Deletes the selected link but keeps its displayed text.
* *Delete Link* - Deletes the selected link and its displayed text.

=== Anchors

An anchor is represented by the icon shown in <<figure-8.02>> and can be referenced in a link:#_links[link] to direct a user to a particular place within a node.  

[[figure-8.02]]
.Figure 8.02
{anchor}

==== Inserting Anchors

. Select *Insert Anchor* from the *Edit* menu to display *Insert Anchor* menu.
. Provide a name for the anchor. 
. Click *OK* to complete the insertion.

==== Referencing Anchors

When link:#_inserting_a_link[inserting a link], select the *To Node* option and add the name of the anchor to the *Anchor Name* textbox. Hovering over an anchor will display its name.

==== Editing Anchors

Right-click an anchor icon to display is options.

* *Cut Anchor* - Moves the selected anchor to your clipboard. The anchor can then be pasted elsewhere.
* *Copy Anchor* - Copies the selected anchor to your clipboard. The copy can then be pasted elsewhere.
* *Delete Anchor* - Deletes the selected anchor.
* *Edit Anchor* - Displays the *Insert Anchor* menu allowing you to rename the anchor.

=== Table of Contents

This feature inserts an unordered, hierarchical list containing a link for every node and header. 

==== Inserting a Table of Contents

[start=1]
. Select *Insert TOC* from the *Edit* menu to display the *Involved Nodes* menu.
. Define the scope of the contents to be included.
+
* *Selected Node only* - Includes only the selected node.
* *Selected Node and Subnodes* - Includes the selected node and its {node-relations}[children].
* *All the Tree* - Includes the entire document.

. Click *OK* to complete the insertion.

==== Updating a Table of Contents

A table of contents does not update as changes are made to the nodes or headers. To update a table of contents, delete the existing TOC and create a new one.

=== Timestamps

By default, this feature inserts the date in time in a format such as YYYY/mm/dd - HH:MM, where Y = year, m = month, d = day, H = hour, and M = minute.

==== Inserting a Timestamp

Select *Insert Timestamp* from the *Edit* menu to insert a timestamp.

==== Formatting a Timestamp

The format of the timestamp can be configured in the link:#_text_and_code[text and code preference menu].

=== Special Characters

Cherrytree provides a function for inserting special characters. 

WARNING: These characters are not converted to their corresponding HTML codes when exported.

==== Inserting Special Characters

[start=1]
. Open the *Edit* menu.
. Hover over *Insert Special Character* to display its submenu.
. Click the character to be inserted.

NOTE: See the link:#_text_and_code[text and code preference menu] to add or remove special characters from the link:#_inserting_special_characters[special character submenu]. That configuration option can also be referenced for a list of supported special characters.

=== Horizontal Rule

By default, this feature inserts a line of 33 `~` characters one line below the selected line. An empty line is inserted one line below the horizontal rule.

WARNING: These characters are not converted to a horizontal rule when exported.

==== Configuring Horizontal Rules

The horizontal rule can be configured in the link:#_text_and_code[text and code preference menu] to insert any sequence of characters.

==== Inserting a Horizontal Rule

Select *Insert Horizontal Rule* from the *Edit* menu to insert a horizontal rule.
