== Objects

Objects can be inserted from the menu bar under *Edit*, <<figure-8.01>>, or the toolbar, <<figure-8.02>>. Some objects can and also be pasted directly into Cherrytree. 

[[figure-8.01]]
.Figure 8.01
{insert-menu}

[[figure-8.02]]
.Figure 8.02
{insert-toolbar}

=== Images

==== Inserting Images

[start=1]
. Open the link:#_objects[*Edit* menu] and click *Insert Image*.
. Select the image to be uploaded and click *Open*. 
. (*Optional*) The selected image will be displayed in a simplistic editor, shown in <<figure-8.03>>, which can be used to rotate or scale the content. 
+
[[figure-8.03]]
.Figure 8.03
{img-props}
+
<<figure-8.03>> has been highlighted to indicate the parts of its interface.

* *Red* - Displays the image uploaded in *Step 2*.
* *Purple* - Allows for the editing of the image's dimensions. Height and Width are linked each other to maintain the content's aspect ratio.
* *Yellow* - Rotate the image counter-clockwise 90&deg;.
* *Green* - Rotate the image clockwise 90&deg;.
. Click *OK* to complete the insertion.

==== Editing Images

Right-click an image to display its menu of options, <<figure-8.04>>.

[[figure-8.04]]
.Figure 8.04
{edit-image}

* *Cut Image* - Move the selected image to your clipboard. The image can then be pasted elsewhere.
* *Copy Image* - Copy the selected image to your clipboard. A copy of the image can then be pasted elsewhere.
* *Delete Image* - Delete the selected image.
* *Edit Image* - Rotate or scale the image, shown in <<figure-8.03>>
* *Save Image as PNG* - Save a copy of the selected image to your computer.
* *Edit Link* - Apply or edit the link of the selected image. See link:#_links[8.5 Links] for more information about links.
* *Dismiss Link* - Remove an existing link from the selected image. This option will only appear if the image has an assigned link.

NOTE: Cherrytree does not support wrapping text around images at this time.

=== Tables

==== Creating a New Table

[start=1]
. Open the link:#_objects[*Edit* menu] and click *Insert Table*.
. (*Optional*) The *Insert Table* menu will be displayed and can be used to define the properties of the table.
+
[[figure-8.05]]
.Figure 8.05
{insert-table}
+
* *Rows* - Defines the number of rows to be in the table in the addition to the header row.
* *Columns* - Defines the number of columns to be in the table.
* *Min Width* - Defines the lowest number of pixels in width that a column must have.
* *Max Width* - Defines the highest number of pixels in width that a column can have.
* *Import from CSV File* - Imports data from a *.csv* file.
+
IMPORTANT: *.csv* data should be separated by a comma delimiter.
+
NOTE: Cherrytree may take a few minutes to upload a large file. Please be patient. 

. Click *OK* to complete the insertion.

==== Managing Columns

Click a column title to display a menu listing actions for that column. <<figure-8.06>>

[[figure-8.06]]
.Figure 8.06
{table-column}

* *Rename Column* - Change the title of the selected column.
* *Delete Column* - Delete the selected column.
* *Add Column* - Add a new column to the right of the selected column.
* *Move Column Left* - Switch the placement of the selected column with that of the column to its immediate left. Nothing will happen if there is no column left of the selected column.
* *Move Column Right* -Switch the placement of the selected column with that of the column to its immediate right.  Nothing will happen if there is no column right of the selected column.

==== Managing Rows

A table row can be edited by right-clicking any of its cells. <<figure-8.07>>

[[figure-8.07]]
.Figure 8.07
{edit-table}

* *Cut Table* - Move the selected table to your clipboard. The table can then be pasted elsewhere.
* *Copy Table* - Copy the selected table to your clipboard. A copy of the table can then be pasted elsewhere.

* *Delete Table* - Delete the selected table.

* *Add Row* - Add a new row underneath the selected row.

* *Cut Row* - Move the selected row to your clipboard. The row can then be pasted elsewhere.

* *Copy Row* - Copy the selected row to your clipboard. A copy of the row can then be pasted elsewhere.

* *Paste Row* - Paste a row from your clipboard underneath the selected row.

* *Delete Row* - Delete the selected row.

* *Move Row Up* - Switch the placement of the selected row with that of the row immediately above it. Nothing will happen if there is no row above the selected row.

* *Move Row Down* - Switch the placement of the selected row with that of the row immediately below it. Nothing will happen if there is no row below the selected row.

* *Sort Rows Descending* - References the first column to sort the selected table numerically then alphabetically, from bottom to top.

* *Sort Rows Ascending* - References the first column to sort the selected table numerically then alphabetically, from top to bottom.

* *Edit Table Properties* - Edit the *Column Properties*, discussed in <<figure-8.05>>, of the selected table.

* *Table Export* - Export the selected table to a *.csv* file containing data separated by comma delimiters.

==== Writing to Tables

Double-click a cell to open a textbox within it.

CAUTION: Clicking outside of a table before closing a textbox will discard all changes to that textbox. To write changes to a textbox within a table cell, you must click to another cell, press *Enter*,  or press *Tab*. This has been reported, but is unlikely to be patched in this version of Cherrytree.

NOTE: Tables currently only support link:#_plain_text[plain text]. 

Right-click the textbox to display a menu of its actions and properties. <<figure-8.08>>

[[figure-8.08]]
.Figure 8.08
{cell-menu}

* *Cut* - Move the selected text to your clipboard. The row can then be pasted elsewhere.
* *Copy* - Copy the selected text to your clipboard. A copy of the table can then be pasted elsewhere.
* *Paste* - Paste the text from your clipboard to the cursor position.
* *Delete* - Delete the selected text.
* *Select All* - Select all of the text within the textbox.
* *Input Methods* - Select from one of the following input methods:
** System (Default)
** None
** Amharic(EZ+)
** Cedilla
** Cyrillic (Transliterated)
** Inuktitut (Transliterated)
** IPA
** Multipress
** Thai-Lao
** Tigrigna-Eritrean (EZ+)
** Tigrigna-Ethiopian (EZ+)
** Vietnamese (VIQR)
** Windows IME
* *Insert Unicode Control Character* - Select from one of the following unicode control characters:
** *LRM* - Left-to-right mark
** *RLM* - Right-to-left mark
** *LRE* - Left-to-right embedding
** *RLE* - Right-to-left embedding
** *LRO* - Left-to-right override
** *RLO* - Right-to-left override
** *PDF* - Pop directional formatting
** *ZWS* - Zero width space
** *XWJ* - Zero width joiner
** *XWNJ* - Zero width non-joiner
* *Insert NewLine* - Adds a newline character to the current cursor position.
+ 
NOTE: This will not be noticeable until the textbox is closed.

=== Codebox

A codebox is a contained, executable section of syntax highlighting, which can be inserted into link:#_rich_text[Rich Text] nodes. A link:#_rich_text[Rich Text] node can contain more than one codebox for any of the link:#_supported_languages[supported languages]. See link:#_automatic_syntax_highlighting[*7.3 Automatic Syntax Highlighting*] for more details about syntax highlighting.

==== Inserting a Codebox

[start=1]
. Click *Edit*, located in the link:#menu-bar[menu bar].
. Click *Insert Codebox* to display the *Insert Codebox* menu, shown in <<figure-8.09>>.
+
[[figure-8.09]]
.Figure 8.09
{insert-codebox}

. (*Optional*) Change the codebox type:
+
* *Plain Text* - Restricts the codebox to link:#_plain_text[plain text].
* *Automatic Syntax Highlighting* - Applies link:#_automatic_syntax_highlighting[automatic syntax highligting] to the codebox. (Default)
* *Choose a language* - Select from any of the link:#_supported_languages[supported languages].

. (*Optional*) - Define the codebox size:
+
* *Width* - Defines the width of the codebox.
** *Pixels* - Defines the width in pixels. (Default)
** *% (Percentage)* -  Defines the width as a percentage. This will assign a dynamic width that changes alongside changes in the window's width.
* *Height* - Defines the height of the codebox in pixels.

. (*Optional*) Select any additional options:
+
* *Show Line Numbers* - Display line numbers within the left margin of the codebox.
* *Highlight Matching Brackets* - Indicate the corresponding bracket of the selected opening or closing bracket. 

. Click *OK* to complete the insertion.

==== Editing a Codebox

Right-click a codebox to display its options. <<figure-8.10>>

[[figure-8.10]]
.Figure 8.10
{edit-codebox}

* *Change CodeBox Properties* - Displays a menu similar to the *Insert CodeBox* menu shown in <<figure-8.09>>.

* *Execute CodeBox Code* - Executes the code within the codebox. See link:#_executing_a_codebox[*Executing a Codebox*] for more details.

* *CodeBox Load From Text File* - Import code from a file. This function is not restricted to files that have a *.txt* extension.

* *CodeBox Save To Text File* - Export the content of a codebox to a file. The file can have any extension. 

* *Cut CodeBox* - Move the selected codebox to your clipboard. The codebox can then be pasted elsewhere.

* *Copy CodeBox* - Copy the selected codebox to your clipboard. A copy of the codebox can then be pasted elsewhere.

* *Delete CodeBox* - Delete the selected codebox.

* *Delete CodeBox Keep Content* - Replace the current codebox with a link:#_plain_text[plain text] copy of its content.

* *Increase CodeBox Width* - Increase the width of the selected codebox by 9% if it is defined as a percentage or 15px if it is defined in pixels.

* *Decrease CodeBox Width* - Decrease the width of the selected codebox by 9% if it is defined as a percentage or 15px if it is defined in pixels.

* *Increase CodeBox Height* - Increase the height of the selected codebox by 15 pixels.

* *Decrease CodeBox Height* - Decrease the height of the selected codebox by 15 pixels.

==== Executing a Codebox

A codebox that is set to link:#_automatic_syntax_highlighting[automatic syntax highlighting] can be executed from Cherrytree, assuming you have its assigned language installed to your machine. 

*To execute a the node:*
[start=1]
. Right-click the codebox.
. Click *Execute Codebox code*.
. When prompted, click *OK* to confirm that you want to execute the code.

Some languages will require a command to be assigned to the language before the code can be executed, shown in <<figure-8.11>>. Please see link:#_plain_text_and_code[*9.4 Plain Text and Code*] for details on assigning a command.

[[figure-8.11]]
.Figure 8.11
{command-warning}

[[file-object]]
=== Files

Any file that is less than 10MB can be attached to a link:#_rich_text[Rich Text] node. link:#_rich_text[Rich Text] nodes can contain any number of attached files. 

==== Inserting a File

[start=1]
. Click *Edit*, located in the link:#menu-bar[menu bar].
. Click *Insert File*.
. Select a file and click *OK*.
+
NOTE: The file must be less than 10MB. 

==== Editing a File

Right-click a node to display its options. <<figure-8.12>>

[[figure-8.12]]
.Figure 8.12
{attach-file}

* *Cut Embedded File* - Move the selected file to your clipboard. The file can then be pasted elsewhere.

* *Copy Embedded File* - Copy the selected file to your clipboard. A copy of the file can then be pasted elsewhere.

* *Delete Embedded File* - Delete the attached file.

* *Open File* - Open the attached file.
+
CAUTION: Attached files should be closed before closing their host document(s).

* *Save As* - Save a copy of the selected, attached file to your machine.

=== Links

Text and images within link:#_rich_text[rich text] nodes can be linked to websites, files, folders, or nodes.

==== Inserting a Link

[start=1]
. (*Optional*) Select the text or image to be linked. If nothing is selected, you will be prompted to provide display text for the link.
. Click *Edit*, located within the link:#menu-bar[menu bar].
. If prompted, enter the display text for the link.
. Click *Insert/Edit Link* to display the *Insert Link* menu shown in <<figure-8.13>>.
. Choose from the following options:
+
[[figure-8.13]]
.Figure 8.13
{insert-link}
+
* *To Website* - Route the link to a website address.
* *To File* - Route the link to a file on your machine.
* *To Folder* - Route the link to a folder on your machine.
* *To Node* - Route the link to a node within the document.
* *Anchor name (Optional)* - Route the link to a particular anchor within the selected node. See link:#_anchors[*8.6 Anchors*] to learn more about anchors.

. Click *OK* to complete the insertion.

==== Editing a Link

Right-click a link to display its options. <<figure-8.14>>

[[figure-8.14]]
.Figure 8.14
{edit-link}

* *Edit Link* - Display the *Insert/Edit* menu, shown in <<figure-8.13>>, for the selected link.
* *Cut Link* - Move the selected link to your clipboard. The link can then be pasted elsewhere.
* *Copy Link* - Copy the selected link to your clipboard. A copy of the link can then be pasted elsewhere.
* *Dismiss Link* - Deletes the selected link, but keeps its displayed text.
* *Delete Link* - Deletes the selected link and its displayed text.

=== Anchors

==== Inserting Anchors

==== Editing Anchors

=== Table of Contents

=== Time Stamps

=== Special characters

=== Horizontal Rule
