== Settings

=== Text and Code

[[figure-9.01]]
.Figure 9.01
{text-code-pref}

==== Text Editor

* *Tab Width* - Defines the number of `space` characters that a `tab` is equal to in width.

* *Insert Spaces Instead of Tabs* - When enabled, replaces one `tab` with a number of `spaces` equal to the number indicated in *Tab Width*.

* *Use Line wrapping* - Restricts lines of text to the current viewport by forcing text to a new line. This does not break a line with `newline` characters and can be toggled as needed, without compromising the line structure of a node.

* *Line Wrapping Indentation* - Defines the alignment of wrapped text compared to the original line. 
** *0* - No indention.
** *Less than 0* - Indents the wrapped lines to the right of the original line by `x` pixels, where `x` represents the provided number.
** *More than 0* - Indents the original line to the right of the wrapped lines by `x` pixels, where `x` represents the provided number.

* *Enable Automatic Indentation* - Aligns new lines with the indention of the previous line.

* *Show Line Numbers* - Displays a numerical index of the lines within the link:#editor[editor].

* *Vertical Space Around Lines* - Defines the number of pixels that separate lines of text.

* *Vertical Space in Wrapped Lines* - Defines the percentage of the *Vertical Space Around Lines* value that applies to wrapped lines.
+
NOTE: This will have no effect if *Vertical Space Around Lines* is set to zero.

==== Miscellaneous

* *Timestamp Format* - Defines the format of a link:#_timestamps[timestamp].
+
See link:#_formatting_timestamps[*Formatting Timestamps*] for a list of timestamp directives or visit the {strftime}[*strftime* documentation] by click the icon next to the timestamp setting, shown in <<figure-9.02>>. 
+
[[figure-9.02]]
.Figure 9.02
{strftime-doc}

* *Horizontal Rule* - Defines the text inserted for a link:#_horizontal_rule[horizontal rule].
* *Special Characters* - Defines the list of special characters to exist in the link:#_inserting_special_characters[*Special Characters*] submenu.
+
New characters can be added to the list by pasting them next to the existing characters. Click the yellow arrow icon, shown in <<figure-9.03>>, to reset to the default list of characters.
+
[[figure-9.03]]
.Figure 9.03
{spec-char-default}

* *Chars to Select at Double Click* - By default, double-clicking text selects the sequence of letters and numbers that are under the mouse pointer and are not separated by whitespace, punctuation, or special characters. Adding characters to the *Chars to Select at Double Click* setting will include those characters in a double-click selection.

==== Formatting Timestamps

The table below, copied from the {strftime}[*strftime* documentation], can be referenced when formatting timestamps in Cherrytree.

[cols=2*,options="header"]
[%autowidth]
|===
|Directive
|Value

| %a | Locale's abbreviated weekday name.
| %A | Locale's full weekday name.
| %b | Locale's abbreviated month name.
| %B | Locale's full month name.
| %c | Locale's appropriate date and time representation.
| %d | Day of the month as a decimal number.
| %H | Hour (24-hour clock) as a decimal number.
| %I | Hour (12-hour clock) as a decimal number.
| %j | Day of the year as a decimal number.
| %m | Month as a decimal number.
| %M | Minute as a decimal number.
| %p | Locale's equivalent of either AM or PM.
| %S | Second as a decimal number.
| %U | Week number of the year (Sunday as the first day of the week) as a decimal number [00,53]. All days in a new year preceding the first Sunday are considered to be in week 0.	
| %w | Weekday as a decimal number.
| %W | Week number of the year (Monday as the first day of the week) as a decimal number [00,53]. All days in a new year preceding the first Monday are considered to be in week 0.	
| %x | Locale's appropriate date representation.
| %X | Locale's appropriate time representation.
| %y | Year without century as a decimal number.
| %Y | Year with century as a decimal number.
| %Z | Time zone name (no characters if no time zone exists).
| %% | A literal '%' character.

|=== 

=== Text

[[figure-9.04]]
.Figure 9.04
{text-pref}

*Enable Smart Quotes Auto Replacement* - When enabled, this converts paired quotation marks on a line to smart quotes, illustrated in <<figure-9.05>>.

[[figure-9.05]]
.Figure 9.05
{smart-quotes}

[[rich-text-pref]]
=== Rich Text

The *Rich Text* preferences menu provides configuration options for link:#_rich_text[Rich Text nodes].

[[figure-9.06]]
.Figure 9.06
{rich-text-pref}

==== Spell Check

* *Enable Spell Check* - Toggles Cherrytree's spell check feature.
+
NOTE: *Enchant* is required for this feature. Please install the this dependency if your application is built from source and you haven't already. See link:#_building_from_source[*3. Building from Source*] for instructions.

* *Spell Check Language* - Defines which language the to spell check. The following languages are available:
** *cs_CZ* - Czech (Czechia)
** *de_DE* - German (Germany)
** *en_Au* - English (Australia)
** *en_GB* - English (Britain)
** *en_US* - English (United States)
** *es* - Spanish
** *fr* - French
** *fr_FR* - French (France)
** *hy_AM* - Armenian (Armenia)
** *it_IT* - Italian (Italy)
** *lt_LT* - Lithuanian (Lithuania)
** *nl* - Dutch
** *pl* - Polish
** *pt_BR* - Portuguese (Brazil)
** *ru_RU* - Russian (Russian Federation)
** *uk_UA* - Ukrainian (Ukraine)

==== Theme

* *Light Background, Dark Text* - Sets the editor background color to white and text color to black.

* *Dark Background, Light Text* - Sets the editor background color to dark blue and text color to white.

* *Custom Background and Text* - Defines custom colors for the editor's background and text.
* *Monospace Background* - Defines the background of monospace text.

==== Miscellaneous

* *Show White Spaces* - Displays character markers over spaces.

* *Highlight Current Line* - When enabled, highlights the line of the cursor position.

* *Expand CodeBoxes Automatically* - Increases the height of codeboxes to fit its content in one viewport.

* *Embedded File Icon Size* - Defines the size of link:#file-object[embedded file] icons.

* *Show File Name on Top of Embedded File Icon* - When enabled, displays the file name above link:#file-object[embedded file] icons.

* *Limit of Undoable Steps Per Node* - Defines the maximum states of a node that Cherrytree tracks and can return to using the *Undo* feature.

=== Plain Text and Code

The *Plain Text and Code* preferences menu provides configuration options for link:#_automatic_syntax_highlighting[automatic syntax highlight] nodes, link:#_plain_text[plain text] nodes, and link:#codebox[codeboxes].

[[figure-9.07]]
.Figure 9.07
{plain-text-code-pref}

==== Text Editor

* *Style Scheme* - Defines the color theme for link:#_automatic_syntax_highlighting[automatic syntax highlighting] nodes, link:#_plain_text[plain text] nodes, and link:#_codebox[codeboxes].
** *Classic*
+
[[figure-9.08]]
.Figure 9.08
{classic-theme}

** *Cobalt*
+
[[figure-9.09]]
.Figure 9.09
{cobalt-theme}

** *Kate*
+
[[figure-9.10]]
.Figure 9.10
{kate-theme}

** *Oblivion*
+
[[figure-9.11]]
.Figure 9.11
{oblivion-theme}

** *Tango*
+
[[figure-9.12]]
.Figure 9.12
{tango-theme}

* *Show White Spaces* - Displays character markers over spaces.

* *Highlight Current Line* - When enabled, highlights the line of the cursor position.

==== Code Execution

This section defines the command, for each language, that runs when a link:#_executing_a_codebox[codebox is executed].

==== Adding a New Command

[start=1]
. Click the `+` icon, shown in <<figure-9.13>>, to display the *Select Element to Add* menu, <<figure-9.14>>.
+
[[figure-9.13]]
.Figure 9.13
{add-command}

. Select a language to apply the new command to.
+
[[figure-9.14]]
.Figure 9.14
{select-language-menu}

. Click *OK*

. Find your new language rule in the list and link:#_editing_a_command[edit the command].

==== Editing a Command

Double-click a command to edit its value.

[[figure-9.15]]
.Figure 9.15
{edit-command}

CAUTION: `<tmp_src_path>` is a variable that represents the codebox or node being executed. It should not be removed from the command.

==== Reset to Default

Click the yellow return arrow to reset to the default list of commands.

[[figure-9.16]]
.Figure 9.16
{reset-commands}

==== Terminal Command 
This is the command line configuration required to execute code within Cherrytree. To configure a terminal, set this option to a command that executes another command within a new instance of your terminal. Use `<command>` as a placeholder for the command to be executed in the new instance.

For example, when a codebox is executed on this machine, <<figure-9.17>>, the following command is used: `start cmd /k "<command>"`.

[[figure-9.17]]
.Figure 9.17
{terminal-execution}

* `start cmd` - opens a new instance of command prompt.
* `/k` - a command line option to execute the text that follows inside quotation marks.
* `<command>` - a variable which represents one of the language-specific commands that are defined in the link:#_code_execution[code execution] options.

NOTE: The language-specific command represented by `<command>` is determined by the language selected in the link:#_codebox[codebox properties]. If, for example, a codebox executed in <<figure-9.17>> is configured for python3, `<command>` represents `python3 <tmp_src_path>`. 

=== Tree 1

The *Tree 1* preferences menu provides configuration options for the link:#tree-view[tree view] panel.

[[figure-9.18]]
.Figure 9.18
{tree1-pref}

==== Theme

* *Light Background, Dark Text* - Sets the tree view background color to white and text color to black.

* *Dark Background, Light Text* - Sets the tree view background color to dark blue and text color to white.

* *Custom Background and Text* - Defines custom colors for the editor's background and text.


==== Default Text Nodes Icons

* *Use Different Cherries per Level* - Assigns a unique, default icon to each group of nodes sharing the same level of hierarchy within a node structure.

* *Use Selected Icon* - Assigns one icon to be the default icon for all nodes.

* *No Icon* - Prevents Cherrytree from assigning icons to nodes by default.

* *Hide Right Side Auxiliary Icon* - Hides icons regarding a node's status, such as the *Read Only* and *Bookmarked* icons.

NOTE: Default icons can be overwritten within the *Use Selected Icon* option of a node's link:#_creating_nodes[property menu].

==== Node Status at Startup

* *Restore Expanded/Collapsed Status* - Nodes of a document retain their expand/collapse state after the document is closed and opened again.

* *Expand all Nodes* - All nodes expand when Cherrytree starts.

* *Collapse all Nodes* - All nodes collapse when Cherrytree starts.

* *Nodes in Bookmarks Always Visible* - {node-relations}[Parents] of bookmarked nodes expand on startup so that all bookmarked nodes are visible within the link:#tree-view[tree view].

=== Tree 2

The *Tree 2* preferences menu is a continuation of link:#_tree_1[*Tree 1*], providing additional configuration options for the link:#tree-view[tree view] panel.

[[figure-9.19]]
.Figure 9.19
{tree2-pref}

==== Miscellaneous

* *Tree Nodes Names Wrapping Width* - Defines the width in Pixels at which text begins to wrap within the link:#tree-view[tree view].

* *Display Tree on Right Side* - Moves the link:#tree-view[tree view] panel to the right side of the window.

* *Move Focus to Text at Mouse Click* - When a node is selected, the editor becomes the active panel, and the cursor is positioned at the beginning of the first line.

* *Expand Node at Mouse Click* - Collapsed nodes expand when they are selected within the link:#tree-view[tree view].

* *Last Visited Nodes on Node Name Header* - Defines the number of most recently visited nodes to display above the editor. <<figure-9.20>>
+
[[figure-9.20]]
.Figure 9.20
{recent-nodes}

=== Fonts

[[figure-9.21]]
.Figure 9.21
{fonts-pref}

* *Rich Text* - Defines the default font family, style, and size applied to Rich Text.

* *Plain Text* - Defines the default font family, style, and size applied to Plain Text.

* *Code Font* - Defines the default font family, style, and size applied to syntax-highlighted text.

* *Tree Font* - Defines the default font family, style, and size applied to text within the link:#tree-view[tree view].

=== Links

[[figure-9.22]]
.Figure 9.22
{links-pref}

==== Custom Actions

* *Enable Custom Web Link Click Action* - Defines a custom command to run when a web link is clicked within Cherrytree.

* *Enable Custom File Link Clicked Action* -  Defines a custom command to run when a file link is clicked within Cherrytree.

* *Enable Custom Folder Link Clicked Action* -  Defines a custom command to run when a folder link is clicked within Cherrytree.

==== Colors

* *To Website* - Defines the default text color of links to websites.

* *To File* - Defines the default text color of links to files.

* *To Node* - Defines the default text color of links to nodes.

* *To Folder* - Defines the default text color of links to folders.

==== Miscellaneous

* *Underline Links* - Apply the pass:[<u>underline</u>] property to all links by default.

* *Use Relative Paths for Files And Folders* - When defining paths for links, use link addresses that are relative to the directory containing the current working document.
+
NOTE: {relative-paths}[Click here] for more information about relative paths.

* *Anchor Size* - Defines the size of the of link:#_anchors[anchor] icons.

=== Toolbar

The *Toolbar* preferences menu provides configuration options for the link:#toolbar[toolbar] panel.

[[figure-9.23]]
.Figure 9.23
{toolbar-pref}

==== Adding Actions to the Toolbar

[start=1]
. Click the `+` icon, shown in <<figure-9.24>> to display the *Select Element to Add* window, <<figure-9.25>>.
+
[[figure-9.24]]
.Figure 9.24
{add-action}

. Select an action to add.
+
[[figure-9.25]]
.Figure 9.25
{select-element-menu}
+
NOTE: The `---------` option represents a vertical divider in the toolbar.
. Click *OK* to complete the addition.

The action can then be dragged up or down to determine its position on the toolbar. Actions are organized from top to bottom in the *Toolbar* preferences menu, which translates to left to right in the actual link:#toolbar[toolbar].

==== Removing Actions from the Toolbar

[start=1]
. Select an action.
. Click the `-` icon, shown in <<figure-9.26>> to remove the selected action from the link:#toolbar[toolbar].
+
[[figure-9.26]]
.Figure 9.26
{remove-action}

==== Reset Toolbar Settings

Click the yellow return button, show in <<figure-9.27>> to return to Cherrytree's default toolbar settings.

[[figure-9.27]]
.Figure 9.27
{default-toolbar}

=== Keyboard Shortcuts

The *keyboard Shortcuts* preferences menu provides configuration options for shortcuts to Cherrytree's features.

[[figure-9.28]]
.Figure 9.28
{keyboard-pref}

==== Editing a Keyboard Shortcut

[start=1]
. Select a shortcut to edit.
. Click the edit shortcut button, shown in <<figure-9.29>> to display the *Edit Keyboard Shortcut* menu, <<figure-9.30>>.
+
[[figure-9.29]]
.Figure 9.29
{edit-shortcut-button}

. Select *No Keyboard Shortcut* to remove a shortcut or toggle any of the three options, *control*, *shift*, and *alt*, and add one or more keys to the adjacent form.
+
[[figure-9.30]]
.Figure 9.30
{edit-shortcut-menu}

. Click *OK* to complete the edit.

==== Reset Keyboard Shortcuts Settings

Click the yellow return button, show in <<figure-9.31>> to return to Cherrytree's default shortcut settings.

[[figure-9.31]]
.Figure 9.31
{reset-shortcuts}

==== Default Keyboard Shortcuts

[cols=2*,options="header"]
[%autowidth]
|===
|Key
|Value

|   | Start a New Instance of Cherrytree
| Ctrl+O | Open a New Cherrytree Document  
| Ctrl+S | Save File
|   | Save File and Vacuum
| Ctrl+Shift+S | Save File As
| Ctrl+Shift+P | Set up the Page for Printing
| Ctrl+P  | Print
| F5  | Execute Code
| Ctrl+Q  | Quit Application
| Ctrl+Shift+Q | Exit from Cherrytree
| Ctrl-Alt-P  | Preferences
|   | Open The Directory with Preferences Files
|   | Check for a Newer Version
| F1 | Application's Online Manual
|   | About Cherrytree
| Ctrl+N  | Add a Node having the Same Parent of the Selected Node
| Ctrl+Shift+N | Add a Child Node to the Selected Node
| Ctrl+Shift+D | Duplicate the Selected Node
| F8 | Insert a Node with Hierarchy Year/Month/Day
|   | Sort the Tree Ascending
|   | Sort the Tree Descending
|   | Sort all the Siblings of the Selected Node Ascending
|   | Sort all the Siblings of the Selected Node Descending
| F2 | Edit the Properties of the Selected Node
| Ctrl+Alt+R  | Toggle the Read Only Property of the Selected Node
|   | Change the Selected Node's Children Syntax Highlighting to the Parent's Syntax Highlighting
|   | Tree Summary Information
| Ctrl+Shift+B | Add the Current to the Bookmarks List
| Ctrl+Alt+B | Remove the Current Node from the Bookmarks List
| Ctrl+Z | Undo Last Operation
| Ctrl+Y | Redo Previously Discarded Operation
| Ctrl+Alt+I | Insert an Image
| Ctrl+Alt+T | Insert a Table
| Ctrl+Alt+C | Insert a CodeBox
| Ctrl+Alt+E | Insert a File
| Ctrl+L | Insert a Link/Edit the Underlying Link
| Ctrl+Alt+A | Insert an Anchor
|  | Insert Table of Contents
| Ctrl+Alt+M | Insert Timestamp
| Ctrl+R | Insert Horizontal Rule
| Ctrl+W | Lower the Case of the Selection/ the Underlying Word
| Ctrl+Shift+W | Upper the Case of the Selection/ the Underlying Word
| Ctrl+G | Toggle the Case of the Selection/ the Underlying Word
|  | Strip Trailing Spaces
| Ctrl+Alt+S | Toggle Enable/Disable Spell Check
| Ctrl+Shift+X | Cut as Plain Text, Discard the Rich Text Formatting
| Ctrl+Shift+C | Copy as Plain Text, Discard the Rich Text Formatting
| Ctrl+Shift+V | Paste as Plain Text, Discard the Rich Text Formatting
| Shift+Alt+X | Cut the Current Row/Selected Rows
| Shift+Alt+C | Copy the Current Row/Selected Rows
| Ctrl+K | Delete the Current Row/Selected Rows
| Ctrl+D | Duplicate the Current Row/Selected Rows
| Alt+Up | Move Up the Current Row/Selected Rows
| Alt+Down | Move Down the Current Row/Selected Rows
| Shift+Alt+F | Change the Color of the Selected Text Foreground
| Shift+Alt+B | Change the Color of the Selected Text Background
| Ctrl+B | Toggle Bold Property of the Selected Text
| Ctrl+I | Toggle Italic Property of the Selected Text
| Ctrl+U | Toggle Underline Property of the Selected Text
| Ctrl+E | Toggle Strikethrough Property of the Selected Text
| Ctrl+1 | Toggle h1 Property of the Selected Text
| Ctrl+2 | Toggle h2 Property of the Selected Text
| Ctrl+3 | Toggle h3 Property of the Selected Text
| Ctrl+0 | Toggle Small Property of the Selected Text
| Ctrl+M | Toggle Superscript Property of the Selected Text
|  | Toggle Subscript Property of the Selected Text
|  | Toggle Monospace Property of the Selected Text
|  | Justify Left the Current Paragraph
|  | Justify Center the Current Paragraph
|  | Justify Right the Current Paragraph
|  | Justify Fill the Current Paragraph
| Ctrl+Alt+1 | Set/Unset the Current Paragraph/Selection as a Bulleted List
| Ctrl+Alt+2 | Set/Unset the Current Paragraph/Selection as a Numbered List
| Ctrl+Alt+3 | Set/Unset the Current Paragraph/Selection as a To-Do List
| F7 | Memory of Latest Text Format Type
| Ctrl+Shift+R | Remove the Formatting from the Selected Text
| Ctrl+F | Find into the Selected Node Content
| Ctrl+Shift+F | Find into All the Tree Nodes Contents
| Ctrl+Alt+F | Find into the Selected Node and Subnodes Contents
| Ctrl+T | Find in Nodes names and Tags
| F3 | Iterate the Last Find Operation
| F4 | Iterate the Last Find Operation in Opposite Direction
| Ctrl+H | Replace into the Selected Node Content
| Ctrl+Shift+H | Replace into All Tree Nodes Contents
| Ctrl+Alt+H | Replace into the Selected Node and Subnodes Contents
| Ctrl+Shift+T | Replace in Nodes Names
| F6 | Iterate the Last Replace Option
| Ctrl+Shift+A | Show Search All Matches Dialog
| F9 | Toggle Show/Hide Tree
|  | Toggle Show/Hide Toolbar
|  | Toggle Show/Hide Node Name Header
| Ctrl+Tab | Toggle Focus Between Tree and Text
| Ctrl+Shift+E | Expand All the Tree Nodes
| Ctrl+Shift+L | Collapse All the Tree Nodes
|  | Increase the Size of the Toolbar Icons
|  | Decrease the Size of the Toolbaar Icons
| F11 | Toggle Full Screen On/Off
|  | Export to PDF
|  | Export to HTML
|  | Export to Multiple Plain Text Files
|  | Export to Single Plain Text File
|  | Export to Cherrytree Document
|  | Add Nodes of Cherrytree File to the Current Tree
|  | Add Nodes from a Plain Text File to the Current Tree
|  | Add Nodes from a Folder of Plain Text Files to the Current Tree
|  | Add Nodes from an HTML File to the Current Tree
|  | Add Nodes from a Folder of HTML Files to the Current Tree
|  | Add Nodes from Basket Folder to the Current Tree
|  | Add Nodes from an EssentialPIM HTML File to the Current Tree
|  | Add Nodes of a Gnote Folder to the Current Tree
|  | Add Nodes of a KeepNote Folder to the Current Tree
|  | Add Nodes of a KeyNote Folder to the Current Tree
|  | Add Nodes of a Knowit File to the Current Tree
|  | Add Nodes of a Leo File to the Current Tree
|  | Add Nodes of a Mempad File to the Current Tree
|  | Add Nodes of a NoteCase File to the Current Tree
|  | Add Nodes of a RedNotebook Folder to the Current Tree
|  | Add Nodes of a Tomboy Folder to the Current Tree
|  | Add Nodes of a Treepad File to the Current Tree
|  | Add Nodes of a TuxCards File to the Current Tree
|  | Add Nodes of a Zim Folder to the Current Tree

|=== 

=== Miscellaneous

[[figure-9.32]]
.Figure 9.32
{misc-pref}

==== System Tray

* *Enable System Tray Docking* - Closing Cherrytree minimizes the application to a background process which can be quickly accessed from the machine's system tray. *AppIndicator* may be required to access Cherrytree from the system tray in Linux. 

* *Start Minimized in the System Tray* - Minimizes Cherrytree to the system tray on startup.

* *Use AppIndicator for Docking* - (Linux only) Uses the appindicator feature to provide quick access to Cherrytree from your system tray.

==== Saving

* *Autosave Every `x` Minutes* - When enabled, saves the working document every `x` minutes, where `x` is the number defined in this setting.

* *Autosave on Quit* - Saves the document upon closing Cherrytree.

* *Create a Backup Copy Before Saving* - Stores a copy of the previous version before saving the new version. Backups are stored in the same directory as the current document. 
+
To open a backup:
+
[start=1]
. Rename the backup file, deleting the `~` characters appended to its extension.
. Open the backup file within Cherrytree.

* *Number of Backups to Keep* - Defines the number of backups to keep. The oldest backup will be removed when this limit is exceeded.

CAUTION: This also applies to autosaves that run on a time interval. For example, if your application is configured to save every 5 minutes, Cherrytree creates a backup every five minutes. When the backup limited is exceeded, a backup is cycled out every 5 minutes.

==== Miscellaneous

* *Automatically Check for Newer Version* - Checks the Cherrytree website on startup to determine if a new version of the application is available for download.

* *Enable Word Count in Statusbar* - Displays the word count of the selected node at the bottom of the main window.

* *Reload Document From Last Session* - Cherrytree opens to the same document that was last opened in the previous session.

* **Reload After External Update to CT* File** - Cherrytree refreshes its instance of a document to reflect changes made to the document from other instances.

WARNING: Cherrytree is not intended to be used as a collaboration tool. *Only one instance of a document should be edited at a time.* Editing two or more instances of a document at the same time yields a high potential for *errors* and *data loss*.

==== Language

Defines the language of Cherrytree's interface. Select from one of the following languages:

* *default* -
* *cs* - Czech
* *de* - German
* *el* - Modern Greek
* *en* - English
* *es* - Spanish
* *fi* - Finnish
* *fr* - French
* *hy* - Armenian
* *it* - Italian
* *ja* - Japanese
* *lt* - Lithuanian
* *nl* - Dutch
* *pl* - Polish
* *pt_BR* - Portuguese (Brazil)
* *ru* - Russian 
* *sl* - Slovenian
* *tr* - Turkish
* *uk* - Ukrainian 
* *zh_CN* - Chinese
